//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VmTips
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipsError
    {
        public int Id { get; set; }
        public string Exception { get; set; }
        public string InnerException { get; set; }
    }
}
