//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VmTips
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipsData
    {
        public int Id { get; set; }
        public string Namn { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public Nullable<bool> HasPayed { get; set; }
        public Nullable<int> Poäng { get; set; }
        public string Finallag1 { get; set; }
        public string Finallag2 { get; set; }
        public string Sverige_Kamerun { get; set; }
        public string Ryssland_Brasilien { get; set; }
        public string Kamerun_Brasilien { get; set; }
        public string Sverige_Ryssland { get; set; }
    }
}
